name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Specify your Java version here
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app
        path: target/*.jar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: spring-boot-app

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        scp -i ${{ secrets.EC2_PRIVATE_KEY }} target/simpotelHotelBooking-0.0.1-SNAPSHOT.jar ec2-user@ec2-13-53-131-29.eu-north-1.compute.amazonaws.com:/home/ec2-user/
        ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@ec2-13-53-131-29.eu-north-1.compute.amazonaws.com "sudo systemctl restart your-app-service"